import Head from 'next/head'
import Grid from '../components/Grid/Grid'
import Header from '../components/Header/Header'
import Headline from '../components/Headline/Headline'
import ThisIsTheWay from '@/components/ThisIsTheWay/ThisIsTheWay'
import Services from '@/components/Services/Services'

export default function Home() {
  return (
    <>
      <Head>
        <title>Gusto Creative House</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Headline />
        <ThisIsTheWay />
        <Services />
        <Grid />
        <section></section>
      </main>
    </>
  )
}
